version: "2"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
  disable:
    - gocyclo
issues:
  exclusions:
    - path: _test\.go
      pattern: "error message to ignore"
